# ----
# Site

title: Dr. Dipak Agrawal's Medicine Blog
url: "https://agrawaldipak.github.io/"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo:
description: Accounts of Interesting Cases from Dr. Agrawal's Clinic.
author:
  name: Dipak Agrawal
  email: dipakag.yeotmal@gamil.com
  twitter:

map:
  latitude: 20.3824977
  longitude: 78.1280496
  address: "Padmavati Hospital, Tilak Wadi, Yavatmal, India"
  url: https://www.google.com/maps/place/Padmavati+Hospital(+Dr+Deepak+Agrawal)/@20.3826864,78.126097,17z/data=!3m1!4b1!4m5!3m4!1s0x3bd3e8afbdfa7819:0x9cc00562db2a67a6!8m2!3d20.3826814!4d78.128291
  zoom: 15

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  staff_members:
    _hide_content: true
    _icon: account_circle

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
          uploads_dir: "/images/post_uploads"
        content:
          width: 1500
          height: 2000
          uploads_dir: "/images/post_uploads"
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover

social_icons:
  - Facebook
  - Email

_comments:
  description: Dr. Dipak Agrawal's Medicine Blog
  blurb: Accounts of Interesting Cases from Dr. Agrawal's Clinic.
